---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - lifecycle.suse.com
  resources:
  - upgradeplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.suse.com
  resources:
  - upgradeplans/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.suse.com
  resources:
  - upgradeplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - upgrade.cattle.io
  resources:
  - plans
  verbs:
  - create
  - get
  - list
  - watch
