# permissions for end users to view upgradeplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upgrade-controller
    app.kubernetes.io/managed-by: kustomize
  name: upgradeplan-viewer-role
rules:
- apiGroups:
  - lifecycle.suse.com
  resources:
  - upgradeplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.suse.com
  resources:
  - upgradeplans/status
  verbs:
  - get
